apiVersion: v1
kind: Secret
metadata:
  name: mern-secrets
  namespace: mern-app
type: Opaque
stringData:
  MONGO_URI: "mongodb://mongo-service:27017/mernapp"
  NODE_ENV: "production"
  PORT: "5000"
  # For frontend (Vite uses VITE_ prefix)
  VITE_API_URL: "http://backend-service:5000"
